4# Generated by Django 5.0.6 on 2024-06-19 01:50

import restaurant_menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0010_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=restaurant_menu.models.default_video_file_path, upload_to='videos/'),
        ),
    ]
