# Generated by Django 4.2.6 on 2024-06-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0012_alter_item_meal_type'),
        ('restaurant_menu', '0012_book_alter_item_meal_type'),
    ]

    operations = [
    ]
