# Generated by Django 5.0.6 on 2024-06-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0012_menucard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucard',
            name='image',
            field=models.ImageField(upload_to='menu_images/'),
        ),
    ]
